redis_addr: "localhost:6379"

database_structure:

  - entity: product
    fields:
      - name: guid
        type: string
      - name: code
        type: string
      - name: name
        type: string
    update-endpoint: update_product
    get-endpoint: get_product

  - entity: category
    fields:
      - name: guid
        type: string
      - name: name
        type: string
    update-endpoint: update_category
    get-endpoint: get_category

  - entity: quantity
    fields:
      - name: guid
        type: string
      - name: name
        type: string
    update-endpoint: update_quantity
    get-endpoint: get_quantity

  - entity: cell
    fields:
      - name: guid
        type: string
      - name: name
        type: string
    update-endpoint: update_cell
    get-endpoint: get_cell

  - entity: warehouse
    fields:
      - name: guid
        type: string
      - name: name
        type: string
    update-endpoint: update_warehouse
    get-endpoint: get_warehouse

  - entity: product-store
    fields:
      - name: product
        type: product
      - name: quantity
        type: quantity
      - name: warehouse
        type: warehouse
      - sum: sum
        type: float
    control-fields: sum
    update-endpoint: update_product_store
    get-endpoint: get_product_store
    lists:
      - name: warehouses
        key_format: product:{productGUID}:quantity:warehouses


  - entity: product-cell
    fields:
      - name: product
        type: product
      - name: cell
        type: cell
      - name: sum
        type: float
    control-fields: sum
    update-endpoint: update_product_cell
    get-endpoint: get_product_cell
    lists:
      - name: cells
        key_format: product:{productGUID}:cells