redis_addr: "localhost:6379"

database_structure:

  entities:
    - entity: product
      fields:
        - name: code
          type: string
        - name: name
          type: string
      update-endpoint: update_product
      get-endpoint: get_product

    - entity: quantity
      fields:
        - name: name
          type: string
      update-endpoint: update_quantity
      get-endpoint: get_quantity

    - entity: cell
      fields:
        - name: name
          type: string
      update-endpoint: update_cell
      get-endpoint: get_cell

    - entity: warehouse
      fields:
        - name: name
          type: string
      update-endpoint: update_warehouse
      get-endpoint: get_warehouse

  accums:
    - accum: product-store
      fields:
        - name: product
          type: product
        - name: quantity
          type: quantity
        - name: warehouse
          type: warehouse
      balance:
        - name: sum
          type: float
      update-endpoint: update_product_store
      get-endpoint: get_product_store

    - accum: product-cell
      fields:
        - name: product
          type: product
        - name: cell
          type: cell
      balance:
        - name: sum
          type: float
      update-endpoint: update_product_cell
      get-endpoint: get_product_cell